### ISSUE TITLE
Add support of with statement for Scoped provider

### ISSUE THREAD

**Issue by rmk135** [rmk135/objects#26]

**Comment by rmk135** [comment]
Scoped provider was removed due it's being has not been justified yet.

**Comment by hakeemta** [comment]
Hi @rmk135,

I have been sifting through this repo for Scoped Provider and how it was conceptualized here. I was wondering if you could shed more light on why its "being" or use not justified?

I have a similar situation as with a web request scope. How do you imagine provisioning for that with the current providers without necessarily tearing down and creating new containers when the scope changes?

I look forward to your thoughts on this. Thanks.

**Comment by rmk135** [comment]
Hi @hakeemta ,

I've left that comment in the early days of the Dependency Injector. When I've seen your question for a 1st time the most fair answer was "I don't remember" 😄.

Speaking seriously, the problem with the scoped provider is that it's problematic to implement the generic one. All web frameworks manipulate the request scope differently.

To implement the scoped provider you just need to get the ``Singleton`` and call its ``.reset()`` method when scope changes.

The ``Scoped`` provider was removed just of that reason. It just was a singleton with a previous sentence as a description.

I post a little example in ``Flask`` that shows request scope provider implementation based on ``Singleton``:

```python
from dependency_injector import providers
from flask import Flask


class Service:
    ...


service_provider = providers.Singleton(Service)


def index_view():
    service_1 = service_provider()
    service_2 = service_provider()
    assert service_1 is service_2
    print(service_1)
    return 'Hello  World!'


def teardown_context(request):
    service_provider.reset()
    return request


app = Flask(__name__)
app.add_url_rule('/', 'index', view_func=index_view)
app.after_request(teardown_context)

if __name__ == '__main__':
    app.run()
```

It produces next output:

```bash
 * Serving Flask app "flask_request_scope" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
<__main__.Service object at 0x1099a9d90>
127.0.0.1 - - [25/Aug/2020 17:33:11] "GET / HTTP/1.1" 200 -
<__main__.Service object at 0x1099a9cd0>
127.0.0.1 - - [25/Aug/2020 17:33:17] "GET / HTTP/1.1" 200 -
<__main__.Service object at 0x1099a9d00>
127.0.0.1 - - [25/Aug/2020 17:33:18] "GET / HTTP/1.1" 200 -
<__main__.Service object at 0x1099a9e50>
127.0.0.1 - - [25/Aug/2020 17:33:18] "GET / HTTP/1.1" 200 -
<__main__.Service object at 0x1099a9d90>
127.0.0.1 - - [25/Aug/2020 17:33:18] "GET / HTTP/1.1" 200 -
```

**Comment by hakeemta** [comment]
@rmk135 Ha! It makes sense now. Thank you.

**Comment by rmk135** [comment]
Hey @hakeemta . There is a new major version released since that answer. You might be interested in per-function execution scope with resource provider and wiring feature. Know more at https://python-dependency-injector.ets-labs.org/providers/resource.html#resources-wiring-and-per-function-execution-scope

**Comment by hakeemta** [comment]
Thanks @rmk135 
I like the fluidity of compounding the wiring with container resource provider. I will see how this applies to my use cases and let you know. Once again, thanks for this recommendation.
